# Generated by Django 5.1.1 on 2024-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, default='Unknown', max_length=25),
        ),
    ]
