# Generated by Django 5.1.1 on 2024-09-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body_text',
        ),
    ]
